### ISSUE TITLE
Defer silently swallows errors?

### ISSUE THREAD

**Issue by hadley** [r-lib/withr#148]
``` r
f <- function() {
  on.exit(stop("!"))
}
f()
#> Error in f(): !

f2 <- function() { 
  withr::defer(stop("!")) 
}
f2()
```

<sup>Created on 2020-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jimhester** [comment]
This seems to be by design, defer includes a `tryCatch()` that explicitly captures errors.

It was originally added to later in https://github.com/kevinushey/later/commit/8ba9ba0fabe812a466e73451f5993d23f86759be.

It is not clear to me if it is really needed however, or just considered useful behavior.

**Comment by hadley** [comment]
I guess the goal is that an error in one deferred operation shouldn't cause others to fail. But maybe any errors should still be recorded and then replayed?

**Comment by gaborcsardi** [comment]
I think this makes sense in most cases, but it would be still nice to get the errors or at least the first error somehow. E.g. in (dev) testthat we don't see any teardown errors currently.
