### ISSUE TITLE
rng_version regression?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/withr#167]
Not exactly a reprex, sorry, but seems like with version 2.4.2 this block:
```
...
    withr::local_rng_version("3.5.0")
    withr::local_seed(42)
...
```
now throws warnings, and generates different random numbers on < R 3.5.3 and > R 3.5.3.

See here: https://github.com/r-lib/cli/runs/2394243818?check_suite_focus=true#step:11:34

**Comment by hadley** [comment]
The warning comes from here: https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/library/base/R/RNG.R#L64

**Comment by hadley** [comment]
Looks like a regression in 2.4.2 from #162

**Comment by lionel-** [comment]
I think there are two issues. With #162, the RNGkinds are set to default instead of using the current values. I think we should switch to `NULL` instead of `"default"`.

The second issue is that `RNGkind()` returns `"rounding"` when the 3.5 RNG is set, but does not accept it back.

```r
local({
  withr::local_rng_version("3.5.0")
  RNGkind()
})
#> [1] "Mersenne-Twister" "Inversion"        "Rounding"

local({
  withr::local_rng_version("3.5.0")
  do.call("RNGkind", as.list(RNGkind()))
})
#> Warning message:
#> In RNGkind("Mersenne-Twister", "Inversion", "Rounding") :
#>   non-uniform 'Rounding' sampler used
```

I'm not sure how to fix this. The problem is that there is no public notion of "unset" value for these RNGkinds. Ideally we'd restore to "unset", not to "Rounding".

**Comment by lionel-** [comment]
I'll just fix this by suppressing warnings when setting to "Rounding".

**Comment by lionel-** [comment]
@gaborcsardi If you have time could you please try removing your cli workaround and use dev withr to double check that this is correctly fixed?

**Comment by gaborcsardi** [comment]
I _think_ I removed my workaround, but nothing is failing with CRAN withr, so I am not entirely sure what is going on.
