### ISSUE TITLE
on.exit calls

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/withr#191]
This might seem nitpicking in R, but I think it is important to learn good practice in general. Whenever you write things like

``` r
restore <- change_something()
on.exit(restore_something(restore), add = TRUE)
...
```

you introduce a potential error. If the code is interrupted after `change_something`, but before `on.exit`, then `restore_something` will never happen. 

Here is an example from devtools:
https://github.com/hadley/devtools/blob/c2ad0729e56990b5c66a4e1ef50f3aaa2b8b9c5a/R/with.r#L36-L41

This is of course everywhere, in base R and CRAN packages, not just in devtools. I think in most cases you can just do something like:

``` r
on.exit(try(restore_something(restore)), add = TRUE)
restore <- change_something()
...
```

i.e. just switch the order of the two expressions, and add a `try()`, in case there is an interruption after `on.exit()`, but before `change_something()`.

**Comment by lionel-** [comment]
Basically the `old <- set(new); on.exit(set(old))` idiom (let's call it the "setter restoration pattern") is unsafe and will cause problems in the long run. Since withr functions are used so deeply in our stack, they have to be as safe as they can. #192 progresses towards this goal by providing the mechanisms to implement the "getter pattern" `old <- get(); on.exit(set(old))`.

In general, I think Gabor is right that we should avoid setter restoration in critical packages in favour of getter restoration.
