### ISSUE TITLE
with_env

### ISSUE THREAD

**Issue by jimhester** [r-lib/withr#23]
Implementation can be simple as

``` r
with_env <- function(code, env = new.env()) {
  base::with(new.env(...), code)
}
with_env({a <- 1;print(a)})
#> [1] 1
a
#> Error: object 'a' not found
```

Useful for test setup, temporary variables you don't want to cleanup ect.

**Comment by krlmlr** [comment]
How's that different from `local({...})`?

**Comment by jimhester** [comment]
It's not, I always manage to forget about `local()` for some reason, might be worth just making an alias `with_env <- base::local` for forgetful people like me, but probably not...

**Comment by krlmlr** [comment]
:+1: for the alias :-) It should perhaps follow the API convention of this package, though.

NB: For this repo, I only get pinged by e-mail explicitly if you @-mention me. (Otherwise it's just like a regularly watched repository until I comment to a thread. Those e-mails are sorted into a different mail folder in my setup.)
