### ISSUE TITLE
local_tempfile() fails to close the connection when used in examples with lines=

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/withr#256]
As seen in {lintr}:

https://github.com/r-lib/lintr/pull/2519

Here's the smallest example I could make, doesn't feel very minimal. I tried stripping out various parts of the Rd to no avail. I still don't understand what's going wrong.

```r
tools::Rd2ex(
  "https://raw.githubusercontent.com/r-lib/lintr/4299569bd8abf9164e7ff9c6405a00dd17a4a842/man/get_r_string.Rd",
  rd<-tempfile()
)
source(rd, local=new.env())
# Error in file(con, "r") : cannot open the connection
# In addition: Warning message:
# In file(con, "r") :
#   cannot open file '/tmp/RtmpHdp9A4/file331646fd2e9b3': No such file or directory
```

**Comment by lionel-** [comment]
See the NEWS file, you need to actively set the `withr.hook_source` option when sourcing outside of the global env.

I would just use `local()` in that example though.

**Comment by lionel-** [comment]
CRAN is sourcing in the globalenv, which explains why `source()` works out of the box.

By the way @gaborcsardi let me know that this only works because your example is conditional. If you remove the condition, the generated R code will no longer be fenced by `source()`, and withr will stop working 100% as expected. The exit handlers will be run after all examples have completed rather than at the end of the particular example withr was used. So `local()` is definitely still recommended in examples.

**Comment by MichaelChirico** [comment]
Got it, thanks for the elaboration. In that case I will just stick with un-hooked file cleanup, using `local()` in examples will be confusing for novice readers IMO.

I see two other CRAN packages that _may_ be affected:

https://github.com/search?q=org%3Acran+path%3A.Rd+%2Fwithr%3A%3Alocal_tempfile%5B%28%5D%2F+-repo%3Acran%2Flintr&type=code
