### ISSUE TITLE
with_handlers

### ISSUE THREAD

**Issue by jimhester** [r-lib/withr#78]
The with version is just `withCallingHandlers()`, but a local_ one would also be interesting...

**Comment by gaborcsardi** [comment]
`withCallingHandlers()` will still error, so that's not good IMO. You need to `tryCatch` and print the  error, no?

Also, I don't think the local_ version is possible. You can't really define handlers that are local to the calling function, can you? You can define global top level ones, but they are undocumented, AFAIR, and have several issues.

**Comment by jimhester** [comment]
I was thinking something like `withCallingHandlers(error = identity)`, but it would have to be a global environment.

Anyway apparently it seems you can do something like

```r
\dontshow{try(}
code
\dontshow{)}
```

So this seems to be unnecessary.
