### ISSUE TITLE
with_environment doesn't actually work very well

### ISSUE THREAD

**Issue by jimhester** [r-lib/withr#95]
It should be rewritten or possibly removed, and definitely needs some examples.

**Comment by rillig** [comment]
As an R newbie, I agree that it would benefit from some examples.

I tried the following code, in various variations, but couldn't find a way to temporarily overwrite the global variable `arg.level`. I still think it is possible using `with_environment`.

~~~r
arg.level <- as.integer(Sys.getenv('LEVEL'))
level.message <- function(...) message('[ ', arg.level, ' ] ', ...)
level.warning <- function(...) level.message('WARNING: ', ...)

test_that('level.warning', {
    output <- ''
    mock_message <- function(...) output <<- paste0(output, ..., '\n')

    arg.level <<- 123  # XXX: should use with_environment instead
    with_mock(message = mock_message, {
        level.warning('mess', 'age', ' text')
    })

    expect_equal(output, '[ 123 ] WARNING: message text\n')
})
~~~

I managed to mock `message`, but since `with_mock` can only mock functions, I'm out of luck here. It would be nice if the examples could cover this case.
